### ISSUE TITLE
MinesweeperBoard.MinesweeperBoard no has test

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/minesweeper#26]
test for the class constructor MinesweeperBoard

**Comment by ezedepetris** [comment]
resolved in this rev [b7953c9]

**Comment by lbuttignol** [comment]
@ezedepetris This test should be stricter. I suggest the next case 
```
MinesweeperBoard board = new MinesweeperBoard( -4,-4,-4);

MinesweeperBoard board = new MinesweeperBoard( 1,1,100);
  
```

**Comment by saiema** [comment]
`MinesweeperBoard` have two constructors
`MinesweeperBoard#MinesweeperBoard(int, int, int)` and `MinesweeperBoard#MinesweeperBoard(int, int)` this issue mentions one constructor but doesn't specify which one.

**Comment by ezedepetris** [comment]
resolved in this rev [0a081e0]

**Comment by saiema** [comment]
Partially resolved, next time consider testing all the properties (in this case, all cells should be closed, unblocked, and the number of cells with mines should be consistent with the constructor and parameters used).
