### ISSUE TITLE
MinesweeperCell.isBlocked has no tests

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/minesweeper#3]
MinesweeperCell.isBlocked should have tests checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine.

**Comment by gamassimino** [comment]
solved in this commit `af5d6ae`

**Comment by nricci** [comment]
The commit you reference is not yours, neither it implements tests for isBlocked

**Comment by saiema** [comment]
The issue is not fully resolved since current tests only verify that after a cell is created it's not blocked.

**Comment by gamassimino** [comment]
fix 429a5d6
